# Generated by Django 4.0.5 on 2022-06-13 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioPost',
            fields=[
                ('idcomentario', models.AutoField(primary_key=True, serialize=False)),
                ('contenido_comentario', models.TextField()),
            ],
            options={
                'db_table': 'comentario_post',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PostBlog',
            fields=[
                ('idpost', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo_post', models.CharField(max_length=200)),
                ('contenido_post', models.TextField()),
                ('fecha_post', models.DateTimeField()),
            ],
            options={
                'db_table': 'post_blog',
                'managed': False,
            },
        ),
    ]
